### ISSUE TITLE
Error: No module named 'psi_update'

### ISSUE THREAD

**Issue by KellyBrewer** [LeqiXu/JointPRS#1]
Hi there, 

I'm trying to run JointPRS after having run PRS-CS a few times. I'm pretty new to python and I'm not familiar with cython. I've done all of your steps for installation and when I attempt to run, I'm getting this error:

"
Traceback (most recent call last):
  File "/hpc/users/brewek04/JointPRS/JointPRS.py", line 6, in <module>
    import mcmc_gtb
  File "/hpc/users/brewek04/JointPRS/mcmc_gtb.py", line 13, in <module>
    import psi_update
ModuleNotFoundError: No module named 'psi_update'
"

Can you let me know how to fix this?

Thank you.

**Comment by LeqiXu** [comment]
Hi there,  

There are a few steps you can try to resolve this issue:  

1. Check if the installation is complete. Ensure all necessary files exist in the `JointPRS` folder. See the reference image below:

![Image](https://github.com/user-attachments/assets/9d8ef013-537a-4960-839f-4ab0b6d0b9d9)  

2. If `psi_update.pyx`, `psi_update.c`, or `psi_update.cpython-*.so` is missing, try rebuilding the Cython files:  

   ```bash
   conda activate JointPRS  
   python setup.py build_ext --inplace  
   ```  

3. If you get an error about Cython not being installed, install it with:  

   ```bash
   conda activate JointPRS  
   conda install cython
   ```  

   Then rerun the build command from step 2.  

4. If the issue persists, try reinstalling everything:  

   ```bash
   conda deactivate  
   conda env remove -n JointPRS  
   conda env create -f environment.yml  
   conda activate JointPRS  
   python setup.py build_ext --inplace  
   ```  

Let me know if you run into any errors in these steps.

**Comment by KellyBrewer** [comment]
Thank you. Reinstalling everything worked as you stated in #4. 

I am attempting to run through the example data using 2 populations, but I'm getting the error:
AttributeError: Module 'scipy' has no attribute 'sqrt'

I'm working on a HPC using python 3.12.5. I'm guessing this is a local problem. Please let me know if there is a fix or if I should reach out to my HPC helpdesk. 

Thanks.

**Comment by LeqiXu** [comment]
JointPRS recommends python = 3.8. Additionally, it will be highly recommended to use the installed conda environment "JointPRS" to prevent any unexpected errors.

**Comment by KellyBrewer** [comment]
Hello, Thank you for your quick reply. 

I am using the JointPRS environment. I changed to python/3.8.2 and now am getting this error:

Traceback (most recent call last):
  File "/hpc/users/brewek04/JointPRS/JointPRS.py", line 5, in <module>
    import parse_genet
  File "/hpc/users/brewek04/JointPRS/parse_genet.py", line 10, in <module>
    import scipy as sp
  File "/hpc/packages/minerva-centos7/py_packages/3.8/lib/python3.8/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/hpc/packages/minerva-centos7/py_packages/3.8/lib/python3.8/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 212, in init scipy._lib._ccallback_c
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

**Comment by LeqiXu** [comment]
Hi, I think this is a local issue that you may need help from your HPC helpdesk.

**Comment by KellyBrewer** [comment]
OK. Thank you.
